### ISSUE TITLE
Counter Balance Sheet

### ISSUE THREAD

**Issue by pwitkow** [BoormanLab-UCD/Latent-Learning-Experiment#13]
We need a new counter balancing sheet with these gift cards: 

Barnes and Nobel
Best Buy
iTunes
Regal
Sephora
Starbucks
REI

Should look something the attached file.
[Counter Balance Sheet.xlsx](https://github.com/BoormanLab-UCD/Latent-Learning-Experiment/files/1032606/Counter.Balance.Sheet.xlsx)

**Comment by janeklee** [comment]
I uploaded the updated Excel sheet on Github; please let me know if you
don't see it.

2017-05-26 10:46 GMT-07:00 pwitkow <notifications@github.com>:
